Sprint №11.
AnatolyB0brov/java-filmorate pull request #3
Opened 2024-09-21 12:11 UTC by AnatolyB0brov

2024-09-22 15:31 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-09-22 15:31 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmService filmService;
При использовании слоеной архитектуры, каждый слой должен строго зависеть от предыдущего и последовательность вызовов не должна нарушаться.

`Controller -> Service -> Storage` 

`Controller` не должен знать ничего про хранилище

2024-09-22 15:31 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserService userService;
Замечание аналогичное тому, что написал про `FilmController`

2024-09-22 15:31 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final UserService userService;
В слоеной архитектуре слои одного уровня (в данном случае сервисы) не должны использовать друг друга. При необходимости можно использовать слои следующего уровня, а именно хранилища

2024-09-22 15:31 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final Comparator<Film> comparator = Comparator.comparing(obj -> obj.getLikes().size());
поля класса обысно хранят в одном месте, либо в начале файла (почти всегда), либо в конце. Не стоит их разбрасывать по всему файлу, это делает файл менее читабельным

2024-09-22 15:31 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        }
Эту логику можно реализовать более эффективно. 
Поскольку при большом количестве друзей у обоих пользователей (например, порядка 10 тысяч). Этот метод может выполняться около 10 секунд, что для веб-сервиса, например, очень критично.

Чтобы сделать этот метод более эффективным можно использовать сортировку идентификаторов друзей, а затем метод двух указателей -- https://www.baeldung.com/java-two-pointer-technique

2024-09-22 15:31 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return Optional.empty();
Можно использовать конструкцию `Optional.ofNullable`:

```java
return Optional.ofNullable(films.get(filmId))
```

2024-09-22 15:31 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage {
Замечания аналогичные `InMemoryFilmStorage`

2024-09-22 15:31 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    }
А что если у разных пользователей будет один и тот же `email`? Мы не выбросим никакой ошибки / предупреждения?

2024-09-23 05:07 UTC, AnatolyB0brov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    }
Не выбросим. В задании же не было указано сделать email уникальным. Иначе по этой же логики и login нужно проверять на уникальность. Для этого отдельно и exception нужно свой писать и обработчик к нему со статусом для контроллера, что также в задании не требовалось. Если каждый раз так додумывать, то я спринт не успею закрыть.

2024-09-23 05:08 UTC, AnatolyB0brov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    }
Будет БД, там сделаю эти поля уникальными.

2024-09-23 18:45 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-09-25 05:19 UTC, merged