Sprint 12.
AnatolyB0brov/java-filmorate pull request #4
Opened 2024-09-26 19:08 UTC by AnatolyB0brov

2024-09-27 21:15 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-09-27 21:15 UTC, LexLippi commented on src/main/resources/schema.sql
> +    duration    INT,
может быть `null`?

2024-09-27 21:15 UTC, LexLippi commented on src/main/resources/schema.sql
> +    name        VARCHAR(255)
может быть `null`?

2024-09-27 21:15 UTC, LexLippi commented on src/main/resources/schema.sql
> +    name VARCHAR(255)
может быть `null`?

2024-09-27 21:15 UTC, LexLippi commented on src/main/resources/schema.sql
> +    genre_id LONG,
могут быть `null`?

2024-09-27 21:15 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/utils/ServicesUtils.java
>  public class ServicesUtils {
Это стоит оформить, как класс-помощник или `@UtilityClass`:

https://www.baeldung.com/java-helper-vs-utility-classes

2024-09-27 21:15 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbGenreStorage.java
> +        String sql = "SELECT DISTINCT genre_id, genres.name AS genre_name " +
А зачем здесь делать `DISTINCT` мы предполагаем, что фильму могли присвоить один и тот же жанр дважды?

2024-09-27 21:15 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbFilmStorage.java
> +    private Film getFilmFromResultSet(ResultSet resultSet) throws SQLException {
Этот метод можно сделать статическим

2024-09-27 21:15 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbFilmStorage.java
> +                "LIMIT ?";
Лучше использовать оператор `FETCH`, так как он определен в стандарте SQL в отличие от `LIMIT`

https://www.geeksforgeeks.org/fetch-in-sql/

2024-09-27 21:15 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else {
`else` не нужен, так как в предыдущей ветке условного оператора, ты делаешь `return`

2024-09-27 21:15 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            Optional<Genre> optionalGenre = genreStorage.getGenreById(genre.getId());
Делать запросы в цикле это плохая затея. Во-первых, мы не контролируем таким образом нагрузку на СУБД, так как не можем оценить какое число запросов выполнится для каждого объекта. Во-вторых, лучше сделать один большой запрос, чем N маленьких

2024-09-27 21:15 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        }
Лучше использовать `.map().orElseThrow()`

2024-09-27 21:15 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (optionalFilm.isPresent()) {
Про это уже писал, лучше использовать `.orElseThrow()`

2024-09-28 08:23 UTC, AnatolyB0brov commented
Привет. Спасибо за ревью.

2024-09-28 08:34 UTC, AnatolyB0brov commented on src/main/resources/data.sql
> +SET referential_integrity TRUE;
Заменил, как ты посоветовал и выхватил вот такой эксепшн
 `Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица содержит записи со значением NULL в поле "ID"
Column "ID" contains null values; SQL statement:
MERGE INTO ratings(name) VALUES ('G'), ('PG'), ('PG-13'), ('R'), ('NC-17') [90081-232]`
![image](https://github.com/user-attachments/assets/55fae7db-7bea-4ecf-8bea-f1d1bcd0a8e5)

2024-09-28 08:34 UTC, AnatolyB0brov commented on src/main/resources/data.sql
> +SET referential_integrity TRUE;
Вернул всё назад

2024-09-29 18:52 UTC, LexLippi approved these changes
Привет!

Хорошая работа!
Некоторые комментарии не были исправлены, я отметил, где не увидел изменений.

Они не являются критичными, поэтому можно исправить их к следующему спринту.

Желаю удачи!

2024-09-29 18:52 UTC, LexLippi commented on src/main/resources/schema.sql
> +    genre_id LONG,
Эти поля необходимо пометить, как `not null`. Иначе в этой таблице может быть идентификатор жанра с неуказанным фильмом и наоборот

2024-09-29 18:52 UTC, LexLippi commented on src/main/resources/schema.sql
> +    status_id LONG,
Кажется, что `status_id` не должен быть `null`

2024-09-29 18:52 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbGenreStorage.java
> +        String sql = "SELECT DISTINCT genre_id, genres.name AS genre_name " +
Не увидел ни ответа на этот вопрос, ни исправлений

2024-10-07 17:49 UTC, merged